// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfkALZ0uooiK-ALPhUhm4b2DbAm8d5ZnA',
    appId: '1:999155541013:web:16c87e030cf0589b9f5a1c',
    messagingSenderId: '999155541013',
    projectId: 'employee-management-syst-fc19d',
    authDomain: 'employee-management-syst-fc19d.firebaseapp.com',
    storageBucket: 'employee-management-syst-fc19d.firebasestorage.app',
    measurementId: 'G-Q6F671L9BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4vLSTM74Q_ZvBfZBNX4_JktOu44EcwsA',
    appId: '1:999155541013:android:cf7697087ab6265d9f5a1c',
    messagingSenderId: '999155541013',
    projectId: 'employee-management-syst-fc19d',
    storageBucket: 'employee-management-syst-fc19d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbdwtObiPkFFQZjYEeINsRDysvYoBxr0M',
    appId: '1:999155541013:ios:7d7578a9885ee2fc9f5a1c',
    messagingSenderId: '999155541013',
    projectId: 'employee-management-syst-fc19d',
    storageBucket: 'employee-management-syst-fc19d.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbdwtObiPkFFQZjYEeINsRDysvYoBxr0M',
    appId: '1:999155541013:ios:7d7578a9885ee2fc9f5a1c',
    messagingSenderId: '999155541013',
    projectId: 'employee-management-syst-fc19d',
    storageBucket: 'employee-management-syst-fc19d.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfkALZ0uooiK-ALPhUhm4b2DbAm8d5ZnA',
    appId: '1:999155541013:web:6d7f2d2a65cd3ebc9f5a1c',
    messagingSenderId: '999155541013',
    projectId: 'employee-management-syst-fc19d',
    authDomain: 'employee-management-syst-fc19d.firebaseapp.com',
    storageBucket: 'employee-management-syst-fc19d.firebasestorage.app',
    measurementId: 'G-YSRP8C0Q2Q',
  );
}
